import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const exportPDF = (project: any) => {
  // if (!project) return;

  // const doc = new jsPDF();

  // // Title
  // doc.setFontSize(18);
  // doc.text(project.name || "Project Summary", 14, 20);

  // // Subtitle
  // doc.setFontSize(11);
  // doc.text(`Generated by Ultra-Cal`, 14, 28);
  // doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 34);

  // // Summary Info
  // const summary = [
  //   ["Total Cooling Load", project.totalCooling || 0],
  //   ["Total Heating Load", project.totalHeating || 0],
  //   ["Total Area", project.totalArea || 0],
  //   ["Units", project.units || "N/A"],
  // ];

  // autoTable(doc, {
  //   startY: 40,
  //   head: [["Metric", "Value"]],
  //   body: summary,
  //   theme: "striped",
  // });

  // // Room Breakdown
  // const roomRows = (project.rooms || []).map((r: any) => [
  //   r.name || "N/A",
  //   r.coolingLoad || 0,
  //   r.heatingLoad || 0,
  //   r.area || 0,
  // ]);

  // autoTable(doc, {
  //   startY: (doc as any).lastAutoTable.finalY + 10,
  //   head: [["Room", "Cooling", "Heating", "Area"]],
  //   body: roomRows,
  //   theme: "grid",
  // });

  // // Footer
  // doc.setFontSize(10);
  // doc.text("© Ultra-Cal — Project Export", 14, 285);

  // // Save file
  // doc.save(`${project.name || "project"}_summary.pdf`);
};
